# Generated by scripts/generate-activity-contracts.ts. Do not edit.
from pydantic import BaseModel, ConfigDict, Field
from partyroom_activity_worker import ActivityDefinition

class SeparateInput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    audio_url: str = Field(alias="audioUrl")

class SeparateOutput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    instrumental_artifact_id: str = Field(alias="instrumentalArtifactId")
    vocals_artifact_id: str = Field(alias="vocalsArtifactId")
    content_type: str = Field(alias="contentType")
    model: str

separate = ActivityDefinition[SeparateInput, SeparateOutput](
    name="media.separate",
    version=2,
    task_queue="stems",
    input_model=SeparateInput,
    output_model=SeparateOutput,
    artifact_slots=["instrumentalArtifactId","vocalsArtifactId"],
)
