# Generated by scripts/generate-activity-contracts.ts. Do not edit.
from pydantic import BaseModel, ConfigDict, Field
from partyroom_activity_worker import ActivityDefinition

class SeparateInput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    audio_url: str = Field(alias="audioUrl")

class SeparateOutput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    instrumental_storage_id: str = Field(alias="instrumentalStorageId")
    vocals_storage_id: str = Field(alias="vocalsStorageId")
    content_type: str = Field(alias="contentType")
    model: str

separate = ActivityDefinition[SeparateInput, SeparateOutput](
    name="media.separate",
    version=1,
    task_queue="stems",
    input_model=SeparateInput,
    output_model=SeparateOutput,
    artifact_slots=["instrumentalStorageId","vocalsStorageId"],
)
