# Generated by scripts/generate-activity-contracts.ts. Do not edit.
from pydantic import BaseModel, ConfigDict, Field
from partyroom_activity_worker import ActivityDefinition

class AnalyzeMelodyInput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    audio_url: str = Field(alias="audioUrl")

class AnalyzeMelodyOutput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    storage_id: str = Field(alias="storageId")
    content_type: str = Field(alias="contentType")
    model: str

analyze_melody = ActivityDefinition[AnalyzeMelodyInput, AnalyzeMelodyOutput](
    name="media.analyzeMelody",
    version=1,
    task_queue="annotations",
    input_model=AnalyzeMelodyInput,
    output_model=AnalyzeMelodyOutput,
    artifact_slots=["storageId"],
)

class AssembleAnnotationsInput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    lyrics_url: str = Field(alias="lyricsUrl")
    melody_url: str = Field(alias="melodyUrl")
    duration: float
    extractor: str
    source_id: str = Field(alias="sourceId")
    title: str | None = None

class AssembleAnnotationsOutput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    annotations_storage_id: str = Field(alias="annotationsStorageId")
    midi_storage_id: str = Field(alias="midiStorageId")
    music_xml_storage_id: str = Field(alias="musicXmlStorageId")
    content_type: str = Field(alias="contentType")

assemble_annotations = ActivityDefinition[AssembleAnnotationsInput, AssembleAnnotationsOutput](
    name="media.assembleAnnotations",
    version=1,
    task_queue="annotations",
    input_model=AssembleAnnotationsInput,
    output_model=AssembleAnnotationsOutput,
    artifact_slots=["annotationsStorageId","midiStorageId","musicXmlStorageId"],
)
