import { resolve } from "node:path";
import type { WireSchema } from "../packages/activities/src/wire";
import { mediaActivities } from "../packages/media-activities/src/registry";

const root = resolve(import.meta.dir, "..");

const pythonTargets = {
  "apps/stem-worker/app/activities_generated.py": ["separate"],
  "apps/lyrics-worker/app/activities_generated.py": ["transcribe"],
  "apps/annotations-worker/app/activities_generated.py": ["analyzeMelody", "assembleAnnotations"],
} as const;

function snakeCase(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replaceAll("-", "_")
    .toLowerCase();
}

function pascalCase(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

function pythonType(schema: WireSchema): string {
  switch (schema.kind) {
    case "string":
      return "str";
    case "artifact":
      return "str";
    case "number":
      return "float";
    case "boolean":
      return "bool";
    case "optional":
      return `${pythonType(schema.value)} | None`;
    case "array":
      return `list[${pythonType(schema.value)}]`;
    case "object":
      throw new Error("Nested object schemas require a named generated model");
  }
}

function model(name: string, schema: WireSchema) {
  if (schema.kind !== "object") throw new Error(`${name} must be an object schema`);
  const fields = Object.entries(schema.fields).map(([wireName, field]) => {
    const pythonName = snakeCase(wireName);
    const optional = field.kind === "optional";
    const assignment =
      pythonName === wireName
        ? optional
          ? " = None"
          : ""
        : ` = Field(${optional ? "default=None, " : ""}alias=${JSON.stringify(wireName)})`;
    return `    ${pythonName}: ${pythonType(field)}${assignment}`;
  });
  return [
    `class ${name}(BaseModel):`,
    "    model_config = ConfigDict(populate_by_name=True)",
    ...fields,
    "",
  ].join("\n");
}

function generatePython(keys: readonly (keyof typeof mediaActivities)[]) {
  const definitions = keys.map((key) => {
    const activity = mediaActivities[key];
    const className = pascalCase(key);
    return [
      model(`${className}Input`, activity.inputSchema),
      model(`${className}Output`, activity.outputSchema),
      `${snakeCase(key)} = ActivityDefinition[${className}Input, ${className}Output](`,
      `    name=${JSON.stringify(activity.name)},`,
      `    version=${activity.version},`,
      `    task_queue=${JSON.stringify(activity.queue.name)},`,
      `    input_model=${className}Input,`,
      `    output_model=${className}Output,`,
      `    artifact_slots=${JSON.stringify(activity.artifactSlots)},`,
      ")",
      "",
    ].join("\n");
  });
  return [
    "# Generated by scripts/generate-activity-contracts.ts. Do not edit.",
    "from pydantic import BaseModel, ConfigDict, Field",
    "from partyroom_activity_worker import ActivityDefinition",
    "",
    ...definitions,
  ].join("\n");
}

for (const [path, keys] of Object.entries(pythonTargets)) {
  await Bun.write(resolve(root, path), generatePython(keys));
}

await Bun.write(
  resolve(root, "packages/media-activities/generated/contracts.json"),
  `${JSON.stringify(
    Object.fromEntries(
      Object.entries(mediaActivities).map(([key, activity]) => [
        key,
        {
          name: activity.name,
          version: activity.version,
          taskQueue: activity.queue.name,
          input: activity.inputSchema,
          output: activity.outputSchema,
          artifacts: activity.artifacts,
        },
      ]),
    ),
    null,
    2,
  )}\n`,
);
