# Generated by scripts/generate-activity-contracts.ts. Do not edit.
from pydantic import BaseModel, ConfigDict, Field
from partyroom_activity_worker import ActivityDefinition

class TranscribeInput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    audio_url: str = Field(alias="audioUrl")

class TranscribeOutput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    storage_id: str = Field(alias="storageId")
    timed_lyrics_storage_id: str = Field(alias="timedLyricsStorageId")
    content_type: str = Field(alias="contentType")
    model: str
    language: str | None = None

transcribe = ActivityDefinition[TranscribeInput, TranscribeOutput](
    name="media.transcribe",
    version=1,
    task_queue="lyrics",
    input_model=TranscribeInput,
    output_model=TranscribeOutput,
    artifact_slots=["storageId","timedLyricsStorageId"],
)
