# Generated by scripts/generate-activity-contracts.ts. Do not edit.
from pydantic import BaseModel, ConfigDict, Field
from partyroom_activity_worker import ActivityDefinition

class TranscribeInput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    audio_url: str = Field(alias="audioUrl")

class TranscribeOutput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    lyrics_artifact_id: str = Field(alias="lyricsArtifactId")
    timed_lyrics_artifact_id: str = Field(alias="timedLyricsArtifactId")
    content_type: str = Field(alias="contentType")
    model: str
    language: str | None = None

transcribe = ActivityDefinition[TranscribeInput, TranscribeOutput](
    name="media.transcribe",
    version=2,
    task_queue="lyrics",
    input_model=TranscribeInput,
    output_model=TranscribeOutput,
    artifact_slots=["lyricsArtifactId","timedLyricsArtifactId"],
)

class AlignLyricsInput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    audio_url: str = Field(alias="audioUrl")
    transcript: str
    language: str

class AlignLyricsOutput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    timed_lyrics_artifact_id: str = Field(alias="timedLyricsArtifactId")
    content_type: str = Field(alias="contentType")
    model: str
    language: str

align_lyrics = ActivityDefinition[AlignLyricsInput, AlignLyricsOutput](
    name="media.alignLyrics",
    version=2,
    task_queue="lyrics",
    input_model=AlignLyricsInput,
    output_model=AlignLyricsOutput,
    artifact_slots=["timedLyricsArtifactId"],
)
